### PR TITLE
editor autosave

### LINKED ISSUE #104: Need the ability to snapshot drafts of exams while editing them
If something goes wrong in the page, React just stops working altogether, and losing all the work isn't very fun for the professor...

### PR DESCRIPTION
**Pull request by kylesferrazza**
- redux-form transition
  - [x] add reset button
  - [x] answers next to info
    - [x] transform for loading
    - [x] transform for submitting
  - fix remaining items
    - [x] show right number of options in Matching
    - [x] CodeTag file contexts for part and question
    - [x] Code starter filepicker
    - [x] ATA select more than one
    - ATA/MC selected answer should move when items are moved
      - [x] ATA
      - [x] MC
- autosave
  - [x] timer
  - [x] reset button does an immediate save

closes #104

### CODE REVIEW

**Comment by blerner** [comment]
For the "Code starter file" stuff -- I think we may want to revisit the design here.  Given that we have a code editor, and it has toolbar abilities for editing locked regions, I think we may want to 
- change the upload schema from an `initial` field that means a file-ref to instead have at most one of `initialFileRef` or `initialCode`
- change the UI for code editing to have a three-way choice: No starter code, Choose a file-ref, or Supply code directly.

**Comment by kylesferrazza** [comment]
- [ ] UI goof: in questions, all the parts appear in the alert at the top, while nothing appears in the card body.  Parts and bodyitems look correct, though
- [ ] UI goof: if the status toast is visible while you click Submit or Cancel, it'll never go away
- [ ] functionality glitch: creating a code question with a supplied starter code with marks prevents autosaving
- [ ] UI glitch: we need to include CodeMirror's paren-matching submode
- [ ] UI glitch: in the exam preview, we should hide the "Choose a file" things anywhere that there are no files needed
- [ ] functionality glitch: when I try to export as archive, I get a file-not-found error for one of the uploaded files (presumably, I'd get an error for all of them, but the first error is fatal as it is)

**Comment by kylesferrazza** [comment]
- [ ] I can't select a checked-ness value for ATA options
- [ ] For MC, I created three options (Yes, No and Huh), and selected Yes.  If I click the move-down button for Yes, the item and its value move down so now it's No, [*] Yes, Huh (which is good) but the mover buttons are still visible.  If I click it again, I now get Yes, No, [*] Huh (which is defintiely bad), and if I click again, I get No, Yes, Huh, with _nothing_ selected
- [ ] For Matching, if I move any of the column A or column B values, the matched values (the answers) don't update in sync
- [ ] As soon as I created an ATA, I started getting autosave errors

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Code.tsx [hunk 1]
```diff
@@ -32,159 +229,133 @@ interface LockStateInfo {
...
-            ...info,
-            prompt: {
-              type: 'HTML',
-              value: newPrompt,
-            },
-          }, value);
-        }}
       />
-      <Form.Group as={Row} controlId={`${qnum}-${pnum}-${bnum}-answer`}>
+      <Form.Group as={Row}>
```
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/Code.tsx:338]: This change in placement of the `controlId` is unfortunate - it breaks some of the accessibility.  (Specifically, labels need to have a `for` field.)

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx [hunk 2]
```diff
@@ -142,33 +143,77 @@ const FileModal: React.FC<FileModalProps> = (props) => {
...
     value,
     onChange,
-    disabled,
+  }: {
+    value: CodeTagInfo['choices'];
+    onChange: (newVal: CodeTagInfo['choices']) => void;
+  } = input;
+  return (
+    <>
+      <Form.Label column sm={2}>Files source</Form.Label>
```
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx:161]: Labels should have `for` fields (or `controlId` in the Form.Group, which indirectly does the same thing).  (To be clear, we've screwed this up elsewhere also, but we shouldn't introduce additional incomplete labels.)

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx [hunk 3]
```diff
@@ -142,33 +143,77 @@ const FileModal: React.FC<FileModalProps> = (props) => {
...
+    value,
+    onChange,
+  } = input;
   const [showModal, setShowModal] = useState(false);
   const examReferences = useContext(ExamFilesContext);
   const questionReferences = useContext(QuestionFilesContext);
   const partReferences = useContext(PartFilesContext);
   let references: FileRef[];
-  switch (choices) {
+  const choice: CodeTagInfo['choices'] = choices.input.value;
```
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx:215]: Again a weird singular/plural inconsistency.  We should rename and be consistent...

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx [hunk 4]
```diff
@@ -179,85 +224,66 @@ const CodeTag: React.FC<CodeTagProps> = (props) => {
...
       break;
     default:
-      throw new ExhaustiveSwitchError(choices);
+      throw new ExhaustiveSwitchError(choice);
   }
   const { fmap } = useContext(ExamContext);
   const filteredFiles = getFilesForRefs(fmap, references);
+  return (
+    <>
+      <Form.Label column sm={2}>Correct answer</Form.Label>
```
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx:233]: Label for...

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx [hunk 5]
```diff
@@ -179,85 +224,66 @@ const CodeTag: React.FC<CodeTagProps> = (props) => {
...
-              active={choices === 'part'}
-              onClick={(): void => {
-                onChange({ ...info, choices: 'part' }, undefined);
-              }}
-            >
-              Files for current part
-            </Button>
-          </ButtonGroup>
-        </Col>
+        <Fields names={['answer', 'choices']} component={EditChoices} />
```
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx:279]: How does this work?  Obviously something redux-forms here that, what, reflectively takes the names given and produces a props object with their values somehow?

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx [hunk 6]
```diff
@@ -1,51 +1,56 @@
...
-    choices,
-    onChange,
+    input,
+    numChoices,
   } = props;
+  const {
+    value,
+    onChange,
+  } = input;
+  const valueI = value ?? -1;
```
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:39]: What does `valueI` mean?

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx [hunk 7]
```diff
@@ -58,254 +63,261 @@ const ChooseRightAnswer: React.FC<{
...
+const RenderValues: React.FC<WrappedFieldProps> = (props) => {
+  const { input } = props;
+  const {
+    value,
+    onChange,
+  }: {
+    value: MatchingPromptWithAnswer[],
+    onChange: (newVal: MatchingPromptWithAnswer[]) => void;
+  } = input;
+  const changeAllAnswers = useCallback((oldVal: number, newVal: number, swap = true): void => {
```
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:279]: This function is definitely confusing.  Some comments would be helpful to explain what it's doing...

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx [hunk 8]
```diff
@@ -1,51 +1,56 @@
-import React, { useState } from 'react';
+import React, { useState, useCallback } from 'react';
```
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:1]: Upon creating a Matching, creating several Column A values and several Column B values, but _not yet setting the correct answers_, autosaving is broken because the exam state doesn't match the schema.  Once one of the answers is non-blank, the schema works again.

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx [hunk 9]
```diff
@@ -58,254 +63,261 @@ const ChooseRightAnswer: React.FC<{
...
+        </Col>
+        <Col className="pr-0">
+          <Field
+            name="html"
+            component={EditHTMLField}
+            theme="bubble"
+            placeholder="Enter a new prompt"
+          />
+        </Col>
+        <Col sm={2}>
```
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:193]: This size isn't quite right:
image

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 8 above)
Comment (blerner) [inline app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:1]: The schema also stipulates the answer value must be >= 0, but None has a value of -1...

File: app/javascript/components/workflows/student/exams/show/types.ts [hunk 10]
```diff
@@ -439,9 +486,24 @@ export interface MatchingState {
...
+}
+
 export type BodyItem =
   HTMLVal | AllThatApplyInfo | CodeInfo | YesNoInfo |
-  CodeTagInfo | MultipleChoiceInfo | TextInfo | MatchingInfo;
+  CodeTagInfo | MultipleChoiceInfo |
+  TextInfo | MatchingInfo;
+
+export type BodyItemWithAnswer =
+  HTMLValWithAnswer | AllThatApplyInfoWithAnswer | CodeInfoWithAnswer | YesNoInfoWithAnswer |
```
Comment (blerner) [inline app/javascript/components/workflows/student/exams/show/types.ts:504]: How can an HTMLVal have an answer?

File: app/models/exam_version.rb [hunk 11]
```diff
@@ -39,12 +39,14 @@ def answers
   end
 
   def default_answers
+    def_answers = answers.map do |ans_q|
+      ans_q.map do |ans_p|
+        ans_p.map { |_| { "NO_ANS": true } }
+      end
+    end
+    def_answers = [[[]]] if def_answers.empty?
```
Comment (blerner) [inline app/models/exam_version.rb:47]: How could this last line be needed?  And how is it of any help, if it implies there's exactly one question with exactly one part with exactly one unanswered body-item?

File: app/models/upload.rb [hunk 12]
```diff
@@ -95,6 +95,9 @@ def make_html_vals(arr)
     arr.map { |i| make_html_val(i) }
   end
 
+  def map_code(code_info)
```
Comment (blerner) [inline app/models/upload.rb:98]: Cleanup?

File: package.json [hunk 13]
```diff
@@ -9,7 +9,8 @@
     "dev": "./bin/webpack-dev-server",
     "lint": "eslint 'app/javascript' --ext 'js,ts,jsx,tsx'",
     "typecheck": "tsc --noEmit --noErrorTruncation --pretty false --incremental false -p .",
-    "uml": "tplant -C --input app/javascript/types.ts --output types.svg"
+    "uml": "tplant -C --input app/javascript/types.ts --output types.svg",
```
Comment (blerner) [inline package.json:12]: When I run this, I get an svg that tells me I need to accept a license somehow.  How?

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 8 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:1]: That was changed in 35310697fcd1e56821013b0ff1c34385c478f92d

Comment (blerner) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:1]: Hmm, I was definitely on the latest commit, and definitely saw a complaint about answers must be "greater than 0, inclusive", so I'm not sure how I was still seeing this answer...

File: app/javascript/components/workflows/professor/exams/new/editor/components/FileUploader.tsx [hunk 14]
```diff
@@ -15,69 +15,67 @@ import { VeryControlledFileViewer } from '@student/exams/show/components/FileVie
 import { handleZip } from '@hourglass/common/archive';
 
 interface FileUploaderProps {
-  files: ExamFile[];
+  value: ExamFile[];
```
[the remark this answers is not in the document]
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/FileUploader.tsx:18]: No, just for our `wrapInput` function to work

File: app/javascript/components/workflows/professor/exams/new/editor/components/FileUploader.tsx [hunk 15]
```diff
@@ -15,69 +15,67 @@ import { VeryControlledFileViewer } from '@student/exams/show/components/FileVie
...
+        <InputGroup>
+          <Form.File
+            // TODO: required
+            onChange={(e): void => {
+              const { files: uploaded } = e.target;
+              const upload = uploaded[0];
+              if (upload) setFile(upload);
+            }}
+            label={curLabel}
+            accept="application/zip,.yaml,.yml"
```
[the remark this answers is not in the document]
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/FileUploader.tsx]: Changed to only support `zip` since that is how we are handling the upload ATM

File: app/javascript/components/workflows/professor/exams/new/editor/components/ShowBodyItems.tsx [hunk 16]
```diff
@@ -61,22 +79,25 @@ const ShowBodyItems: React.FC<BodyItemsProps> = (props) => {
             </Dropdown.Item>
             <Dropdown.Item
               onClick={(): void => {
-                addBodyItem(numBodyItems, {
+                fields.push({
                   type: 'Code',
-                  initial: '',
                   lang: 'text/plain',
```
[the remark this answers is not in the document]
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/ShowBodyItems.tsx]: Went with #1

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Code.tsx [hunk 17]
```diff
@@ -1,23 +1,220 @@
...
+};
+
+const EditCodeAnswerValues: React.FC<{
+  lang: CodeInfo['lang'];
+  onChangeLang: (newLang: CodeInfo['lang']) => void;
+  value: CodeState;
+  onChangeVal: (newVal: CodeState) => void;
+}> = (props) => {
+  const {
+    lang,
```
[the remark this answers is not in the document]
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Code.tsx:69]: yes

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx (hunk 5 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx:279]: `Field` grabs a key in the state relative to the last `FormSection`.
`Fields` grabs more than one at a time.
https://redux-form.com/8.3.0/docs/api/fields.md/

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 6 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:39]: Just moved from your code :)

**Comment by blerner** [comment]
Oh hell.  Our handling of marks is horribly broken, because of the matchbrackets extension: try creating a Code question in Racket mode, and _slowly_ type in `(define foo (* 3 5))`.  Every parenthesis will be marked as readonly.

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 7 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:283]: does that help?

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 8 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:1]: Unable to repro

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 9 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:192]: I'm seeing this:
image

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 8 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:1]: You may not have restarted the server? The schema objects are static, and the server needs to be restarted to read them again.

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 7 above)
Comment (blerner) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:283]: It explains what your code is doing, but now I'm not convinced it's right.  Basically we need to figure out whether we're _swapping_ two items, or _moving_ one item to a new index.  In the code I'd originally written, I was _moving_ an item from one index to another, so everything between those two indices (inclusive) would get shifted up or down by one.  It looks like your code is swapping two items, but then I'm not following why there's an optional `swap` parameters.

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 8 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:1]: Is this because you didn't have the schema change?

File: app/javascript/components/workflows/student/exams/show/types.ts (hunk 10 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/student/exams/show/types.ts:504]: It needs to have a `{ NO_ANS: true }` for rails to not throw it away.

The type is `answer: NoAnswerState`

File: app/models/exam_version.rb (hunk 11 above)
Comment (kylesferrazza) [reply app/models/exam_version.rb:47]: It fixes showing a question/part without sub-parts/items - we rely on answers being a 3d array in multiple places, and indexing with `[]` on undefined throws an error.

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 8 above)
Comment (blerner) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:1]: That might be it

Comment (blerner) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:1]: Quite possibly.  Trying again now, and I can't seem to reproduce what I had either.

File: package.json (hunk 13 above)
Comment (kylesferrazza) [reply package.json]: It said you accepted the license by opening the svg :)
And it was just blank because the file `app/javascript/types.ts` doesn't exist

**Comment by kylesferrazza** [comment]
> Oh hell. Our handling of marks is horribly broken, because of the matchbrackets extension: try creating a Code question in Racket mode, and _slowly_ type in `(define foo (* 3 5))`. Every parenthesis will be marked as readonly.

Let's remove matchbrackets and open it as an issue?

**Comment by blerner** [comment]
Yeah, and matchbrackets doesn't quite do what I need it to, anyway.  Pyret wrote its own version, and I'll need to monkeypatch the builtin matchbrackets to more closely mimic that.  Ugh.

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 7 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:283]: If you move a matching answer from index 1 to index 2, all of the prompts that used to have 1 for an answer need to now have 2, and all of the prompts that used to have 2 for an answer need to now have 1 (they swap).

Swap is false for removing - if I remove at index 2, I want every prompt with answer 2 to be changed to -1, leave previous -1 answers alone, and any answer greater than 2 needs to be subtracted by 1 to account for the removed answer.

Comment (blerner) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx:283]: Those sound like two completely different functions -- one for swapping and one for deleting.  Seems to me that `renderValue` should take in two callbacks, instead: `swapAnswersAt(from, to)` and `deleteAnswer(index)`

File: app/javascript/components/workflows/professor/exams/new/editor/components/BodyItem.tsx [hunk 18]
```diff
@@ -1,60 +1,99 @@
...
+  return (
+    <FormSection name={memberName}>
+      {body}
+    </FormSection>
+  );
 };
 
-const WrappedBody: React.FC<BodyProps> = (props) => {
+export interface BodyProps {
+  memberName: string;
```
[the remark this answers is not in the document]
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/BodyItem.tsx:77]: This is so that the bodyitem knows its address into the store. This way we can either directly render the HTML for editing, or render a FormSection that is already prefixed to the current BodyItem.

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx (hunk 7 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/Matching.tsx]: Yes, that's better

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx (hunk 2 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx:161]: These are inside a form group with `controlId` set.

File: app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx (hunk 4 above)
Comment (kylesferrazza) [reply app/javascript/components/workflows/professor/exams/new/editor/components/questions/CodeTag.tsx:233]: Inside a Group with `controlId`
